org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
## Mod
mod_id=xaeronav
mod_name=XaeroNav
mod_version=0.1.0
mod_group_id=net.prason.xaeronav
mod_authors=Prason
mod_description=Google Maps-style shortest path overlay for Xaero's Map and Minimap.
mod_license=MIT
## Deps
minecraft_version=1.21.1
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)
